### ISSUE TITLE
BlurMatrix throws an error when called

### ISSUE THREAD

**Issue by shssoichiro** [Setsugennoao/vs-rgtools#53]
This is likely caused by #50.

```
Traceback (most recent call last):
  File "myscript.vpy", line 29, in <module>
    clip = vsdehalo.smooth_dering(clip)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jholm\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsdehalo\denoise.py", line 102, in smooth_dering
    smoothed = smooth(work_clip, planes)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jholm\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsdenoise\prefilters.py", line 230, in __call__
    out = _run(clip, planes, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jholm\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsdenoise\prefilters.py", line 74, in _run
    return min_blur(clip, int(pref_type._name_[-1]), planes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jholm\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsrgtools\blur.py", line 183, in min_blur
    blurred = BlurMatrix.BINOMIAL(radius=radius, mode=mode)(clip, planes=planes)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jholm\AppData\Local\Programs\Python\Python312\Lib\site-packages\vsrgtools\enum.py", line 183, in __call__
    if self.mode.is_spatial:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'is_spatial'
```

**Comment by Ichunjo** [comment]
Fixed in https://github.com/Jaded-Encoding-Thaumaturgy/vs-denoise/pull/142
